project:
  type: website

website:
  title: "This is Not the Social Vulnerability Index"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: https://www.arcgis.com/apps/InteractiveLegend/index.html?appid=4d92395405c844a49a36eea90aa6bbfb
        icon: map

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



